### ISSUE TITLE
Wrong file type and exception in CodeStyle when bundled YAML plugin is present

### ISSUE THREAD

**Issue by mxxcon** [vermut/intellij-ansible#14]
When I go to Editor->Code Style->YAML/Ansible I get the following error:
```java
@NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType(TabbedLanguageCodeStylePanel.java:588)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.createHighlighter(TabbedLanguageCodeStylePanel.java:580)
	at com.intellij.application.options.CodeStyleAbstractPanel.a(CodeStyleAbstractPanel.java:377)
	at com.intellij.application.options.CodeStyleAbstractPanel.updatePreview(CodeStyleAbstractPanel.java:171)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:117)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:94)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.<init>(TabbedLanguageCodeStylePanel.java:556)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.addIndentOptionsTab(TabbedLanguageCodeStylePanel.java:104)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.initTabs(TabbedLanguageCodeStylePanel.java:86)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.f(TabbedLanguageCodeStylePanel.java:140)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.getPreviewText(TabbedLanguageCodeStylePanel.java:217)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:148)
	at com.intellij.application.options.CodeStyleAbstractPanel.<init>(CodeStyleAbstractPanel.java:105)
	at com.intellij.application.options.TabbedLanguageCodeStylePanel.<init>(TabbedLanguageCodeStylePanel.java:68)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$SimpleCodeStyleMainPanel.<init>(NeonCodeStyleSettingsProvider.java:42)
	at cz.juzna.intellij.neon.editor.NeonCodeStyleSettingsProvider$1.createPanel(NeonCodeStyleSettingsProvider.java:35)
	at com.intellij.application.options.CodeStyleAbstractConfigurable.createComponent(CodeStyleAbstractConfigurable.java:49)
	at com.intellij.application.options.codeStyle.NewCodeStyleSettingsPanel.<init>(NewCodeStyleSettingsPanel.java:45)
	at com.intellij.application.options.CodeStyleSchemesConfigurable$2.createPanel(CodeStyleSchemesConfigurable.java:232)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.a(CodeStyleMainPanel.java:223)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.d(CodeStyleMainPanel.java:217)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel.access$000(CodeStyleMainPanel.java:43)
	at com.intellij.application.options.codeStyle.CodeStyleMainPanel$3.run(CodeStyleMainPanel.java:146)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vermut** [comment]
Hm, what is the version?

**Comment by mxxcon** [comment]
PyCharm 4.5 and plugin 0.7.2

**Comment by vermut** [comment]
Cannot repeat it. Community edition. We had similar #6 which was fixed. Can you try it on different clean computer? Maybe some wrong settings are cached somewhere?..

**Comment by mxxcon** [comment]
Just updated to plugin 0.7.3, cleared cache as https://www.jetbrains.com/pycharm/help/cleaning-system-cache.html, uninstalled the plugin, manually deleted all remaining files, reinstalled plugin, still crashes. :/

**Comment by awinter125** [comment]
Same for me on pycharm 4.5
@NotNull method com/intellij/application/options/TabbedLanguageCodeStylePanel$MyIndentOptionsWrapper.getFileType must not return null

**Comment by mxxcon** [comment]
Just upgraded to PyCharm 4.5.2 PE and still this plugin crashes.
Is there somehow else I can help you troubleshoot this?(I do not know java)

**Comment by vermut** [comment]
Yes, got it on fresh PyCharm 4.5.2 PE

**Comment by vermut** [comment]
It's truly in conflict with official Yaml plugin. Gotta think of something...

**Comment by vermut** [comment]
Will as Intellij https://youtrack.jetbrains.com/issue/PY-16261

**Comment by vermut** [comment]
And another one https://youtrack.jetbrains.com/issue/PY-17145

**Comment by vermut** [comment]
Try 0.8.0

**Comment by mxxcon** [comment]
Confirming that 0.8.0 no longer crashes with PyCharm 4.5.4 PE :+1:
